import { Router, Request, Response } from 'express';
import { getTelemetryMetrics, getAllTraces, sanitizeTrace, recordTrace } from '../telemetry/index.js';
import { runGrowthAgent } from '../agent/runGrowthAgent.js';
import { clearLatestProposal, getLatestProposal } from '../agent/growthAgent.js';
import { evaluateProposal } from '../gateway/policyEngine.js';
import { createRazorpayOrder, RazorpayOrderResult } from '../payments/razorpayClient.js';

const router = Router();

router.get('/health', (req: Request, res: Response) => {
  res.json({ status: 'ok', message: 'AgentRail Backend is healthy' });
});

/**
 * POST /api/chat
 * Primary entry point connecting Buyer Chat UI to the Growth Agent and RailFence Gateway pipeline.
 *
 * Flow:
 * 1. Executes Growth Agent with buyer message.
 * 2. If a TransactionProposal was generated by the agent:
 *    a. Evaluates proposal against deterministic RailFence policy engine.
 *    b. If APPROVED: executes test Razorpay order creation via official SDK.
 *    c. If BLOCKED: skips payment execution completely (0 Razorpay API calls).
 *    d. Records immutable decision trace log.
 * 3. Returns sanitized execution output (text, proposal, evaluation, razorpayOrder, traceId).
 *    Guarantees zero leakage of private floor prices or secret cost structures.
 */
router.post('/chat', async (req: Request, res: Response) => {
  try {
    const { message, sessionId = 'sess_buyer_01', buyerId = 'buyer_default' } = req.body || {};

    if (!message || typeof message !== 'string' || message.trim() === '') {
      return res.status(400).json({ success: false, error: 'Message string is required' });
    }

    // Reset proposal buffer for session to capture fresh tool calls
    clearLatestProposal(sessionId);

    const startTime = Date.now();
    const agentText = await runGrowthAgent(message);
    const negotiationTimeMs = Date.now() - startTime;

    // Check if Growth Agent generated a formal TransactionProposal payload
    const proposal = getLatestProposal(sessionId);

    if (!proposal) {
      // Non-transactional response (catalog search / query)
      return res.json({
        success: true,
        text: agentText,
        proposal: null,
        evaluation: null,
        razorpayOrder: null,
        traceId: null,
      });
    }

    // Ensure proposal carries request session and buyer identity
    proposal.sessionId = sessionId;
    proposal.buyerId = buyerId;

    // Evaluate proposal against RailFence Policy Gateway
    const evaluationResult = evaluateProposal(proposal);

    let razorpayResult: RazorpayOrderResult | undefined = undefined;

    // Execute Razorpay order ONLY IF proposal is APPROVED by RailFence
    if (evaluationResult.status === 'APPROVED') {
      try {
        razorpayResult = await createRazorpayOrder(proposal, evaluationResult);
      } catch (err: any) {
        console.error('[Razorpay Order Error]', err.message);
        razorpayResult = {
          success: false,
          error: err.message || 'Razorpay order creation failed',
          contractHash: evaluationResult.contractHash,
        };
      }
    }

    // Record immutable decision trace log
    const trace = await recordTrace({
      proposal,
      evaluationResult,
      razorpayResult,
      negotiationTimeMs,
    });

    // Sanitize response to guarantee zero leakage of private floor prices
    res.json({
      success: true,
      text: agentText,
      proposal: sanitizeTrace(proposal),
      evaluation: sanitizeTrace(evaluationResult),
      razorpayOrder: razorpayResult ? sanitizeTrace(razorpayResult) : null,
      traceId: trace.traceId,
    });
  } catch (error: any) {
    console.error('[Chat Endpoint Error]', error);
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to process chat message',
    });
  }
});

/**
 * GET /api/metrics
 * Exposes aggregated growth telemetry metrics (AOV, uplift, block counts, etc.).
 */
router.get('/metrics', async (req: Request, res: Response) => {
  try {
    const metrics = await getTelemetryMetrics();
    res.json({ success: true, metrics });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message || 'Failed to fetch telemetry metrics' });
  }
});

/**
 * GET /api/traces
 * Exposes historical decision traces for telemetry audit log and dashboard.
 * Ensures zero leakage of private merchant pricing/floor prices.
 */
router.get('/traces', async (req: Request, res: Response) => {
  try {
    const traces = await getAllTraces();
    const sanitizedTraces = sanitizeTrace(traces);
    res.json({ success: true, count: sanitizedTraces.length, traces: sanitizedTraces });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message || 'Failed to fetch execution traces' });
  }
});

export default router;
