import { z } from 'zod';

/**
 * Item schema within a TransactionProposal.
 * Tracks SKU, quantity, proposed unit price, and original unit price.
 */
export const TransactionProposalItemSchema = z.object({
  sku: z.string().min(1),
  quantity: z.number().int().positive(),
  proposedUnitPrice: z.number().positive(),
  originalUnitPrice: z.number().positive(),
});

export type TransactionProposalItem = z.infer<typeof TransactionProposalItemSchema>;

/**
 * Allowed revenue growth action classifications.
 */
export const GrowthActionEnum = z.enum(['upsell', 'cross_sell', 'bundle', 'upgrade', 'none']);
export type GrowthAction = z.infer<typeof GrowthActionEnum>;

/**
 * TransactionProposal Schema
 * Formal proposal contract generated by the Growth Agent upon buyer purchase intent.
 * Evaluated by the deterministic Trust Gateway (M7) before any execution.
 */
export const TransactionProposalSchema = z.object({
  transactionId: z.string().uuid(),
  sessionId: z.string().min(1),
  buyerId: z.string().min(1),
  items: z.array(TransactionProposalItemSchema).min(1),
  proposedDiscountPercent: z.number().min(0).max(100),
  proposedTotal: z.number().positive(),
  currency: z.string().default('INR'),
  appliedGrowthActions: z.array(GrowthActionEnum),
  negotiationContext: z.string(),
});

export type TransactionProposal = z.infer<typeof TransactionProposalSchema>;

/**
 * Validates a payload against the TransactionProposal schema.
 * Throws a ZodError if validation fails.
 */
export function validateTransactionProposal(data: unknown): TransactionProposal {
  return TransactionProposalSchema.parse(data);
}
